service: sftp-service

provider:
  name: aws
  runtime: nodejs10
  stage: dev
  region: us-east-1
  role: arn:aws:iam::649633963864:role/service-role/ftp-lambda-ip-role

functions:
  uploadFtp:
    handler: handler.uploadFtp
